import {mkdir,writeFile} from "node:fs/promises";
import {exercises} from "../src/exercises.mjs";
import {demoProgram} from "../src/demo-program.mjs";
import {animationAuditRows,renderExerciseSvg} from "../src/animation-scenes.mjs";
import {animationContrasts} from "../src/animation-audit.mjs";

const esc = value => String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const list = items => `<ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;

function libraryCard(item){
  const haystack=[item.nom,item.famille,...item.muscles,...item.materiel,...item.environnement].join(" ");
  return `<article class="exercise-card" data-family="${esc(item.famille)}" data-search="${esc(haystack)}"><a href="${item.url}" aria-label="Voir ${esc(item.nom)}"><div class="card-visual"><img src="${item.animation}" alt="" loading="lazy" width="640" height="480"></div><div class="card-body"><div class="tag-row"><span class="tag">${esc(item.famille)}</span><span class="tag level">${esc(item.niveau_min)}</span></div><h2 class="card-title">${esc(item.nom)}</h2><p class="card-desc">${esc(item.environnement.join(" · "))} · ${esc(item.materiel.join(", "))}</p><span class="arrow">Voir le mouvement →</span></div></a></article>`;
}

function libraryPage(rows){
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#ffffff"><meta name="description" content="Bibliothèque centrale des mouvements RESET28 : exercices simples, progressifs et adaptés à la maison ou à la salle."><title>Bibliothèque d'exercices · RESET28 Mouvement</title><link rel="icon" href="assets/logo/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/styles.css"></head><body><a class="skip" href="#main">Aller au contenu</a><header class="site-header"><div class="shell header-inner"><a class="brand" href="./"><span class="brand-mark">R28</span><span>RESET28</span></a><a class="nav-link" href="clients/DEMO/">Voir le client test</a></div></header><main id="main"><section class="hero"><div class="shell"><p class="eyebrow">RESET28 · Bouger simplement</p><h1>Bibliothèque<br>d'exercices</h1><p class="lead">Des mouvements clairs, progressifs et rapides à consulter depuis un téléphone.</p><div class="notice"><strong>Une fiche, un mouvement.</strong>Regarde l'animation, lis les trois étapes, puis privilégie une exécution confortable et contrôlée.</div></div></section><section class="controls" aria-label="Filtrer la bibliothèque"><div class="shell"><div class="search-wrap"><label class="skip" for="search">Rechercher un exercice</label><input class="search" id="search" type="search" placeholder="Rechercher : squat, dos, élastique…" autocomplete="off"></div><div class="filters" role="group" aria-label="Familles de mouvements">${["Tous","Bas du corps","Poussée","Tirage / dos","Épaules","Tronc","Corps entier"].map((x,i)=>`<button class="chip" data-family="${esc(x)}" aria-pressed="${i===0}">${esc(x)}</button>`).join("")}</div><div class="library-meta"><span id="result-count">${rows.length} exercices</span><span>Maison · Salle</span></div></div></section><section class="shell exercise-grid" id="exercise-grid" aria-live="polite">${rows.map(libraryCard).join("")}</section></main><footer class="site-footer"><div class="shell footer-inner"><span>RESET28 · Simple. Personnalisé. Applicable.</span><a href="docs/sources.html">Sources & cadre de sécurité</a></div></footer><script src="assets/js/library.js" defer></script></body></html>`;
}

function clientPage(program, rows){
  const bySlug=new Map(rows.map(x=>[x.slug,x]));
  const weeks=program.weeks.map(w=>`<section class="week" id="semaine-${w.number}"><div class="week-head"><div><div class="week-kicker">Semaine ${w.number}</div><h2>Semaine ${w.number}</h2></div><div class="week-focus">${esc(w.focus)}</div></div>${w.sessions.map(s=>`<article class="session"><div class="session-head"><h3>${esc(s.name)}</h3><span class="duration">${esc(s.duration)}</span></div><div class="program-list">${s.items.map(([slug,dose,rest])=>{const x=bySlug.get(slug);return `<a class="program-item" href="../../${x.url}"><img class="program-thumb" src="../../${x.animation}" alt="" loading="lazy" width="52" height="52"><div><div class="program-name">${esc(x.nom)}</div><div class="program-dose">${esc(dose)}</div></div><div class="program-rest">Repos ${esc(rest)}</div><span class="program-arrow" aria-hidden="true">→</span></a>`}).join("")}</div></article>`).join("")}</section>`).join("");
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#ffffff"><meta name="robots" content="noindex,nofollow"><title>${esc(program.client.display_name)} · RESET28 Mouvement</title><link rel="icon" href="../../assets/logo/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../../assets/css/styles.css"></head><body><a class="skip" href="#main">Aller au contenu</a><header class="site-header"><div class="shell header-inner"><a class="brand" href="../../"><span class="brand-mark">R28</span><span>RESET28</span></a><a class="nav-link" href="../../">Bibliothèque</a></div></header><main id="main"><section class="client-hero"><div class="shell"><p class="eyebrow">RESET28 · Ton mouvement</p><h1>Le reset de<br><span>${esc(program.client.display_name)}</span></h1><p class="client-title">${esc(program.client.title)}</p><p class="client-dates">${esc(program.client.dates)}</p><span class="client-notice">${esc(program.client.notice)}</span></div></section><div class="shell"><section class="quick-card"><h2>Ton minimum viable</h2><p>${esc(program.minimum_viable)}</p><ul>${program.reminders.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section><nav class="week-nav" aria-label="Accès rapide aux semaines">${program.weeks.map(w=>`<a href="#semaine-${w.number}" aria-label="Aller à la semaine ${w.number}">${w.number}</a>`).join("")}</nav><div id="program-root">${weeks}</div></div></main><footer class="site-footer"><div class="shell footer-inner"><span>RESET28 · Le sport complète le RESET.</span><a href="../../">Bibliothèque des mouvements</a></div></footer></body></html>`;
}

function exercisePage(item,bySlug){
  const reg=item.regression?bySlug.get(item.regression):null,prog=item.progression?bySlug.get(item.progression):null;
  const fact=(label,value)=>`<span class="fact"><strong>${label}</strong> ${esc(value)}</span>`;
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#ffffff"><meta name="description" content="${esc(item.description)}"><title>${esc(item.nom)} · RESET28 Mouvement</title><link rel="stylesheet" href="../../assets/css/styles.css"></head><body><a class="skip" href="#main">Aller au contenu</a><header class="site-header"><div class="shell header-inner"><a class="brand" href="../../"><span class="brand-mark">R28</span><span>RESET28</span></a><a class="nav-link" href="../../">Bibliothèque</a></div></header><main class="exercise-main" id="main"><div class="shell"><a class="back-link" href="../../">← Tous les exercices</a><div class="exercise-layout"><div><p class="eyebrow">${esc(item.famille)} · ${esc(item.niveau_min)}</p><h1 class="exercise-title">${esc(item.nom)}</h1><p class="exercise-subtitle">${esc(item.description)}</p><div class="facts">${fact("Lieu :",item.environnement.join(" / "))}${fact("Matériel :",item.materiel.join(", "))}${fact("Zones :",item.muscles.join(", "))}</div><div class="exercise-content"><section class="info-card"><h2>Position et exécution</h2><ol>${item.instructions.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></section><section class="info-card"><h2>Les points qui comptent</h2>${list(item.points_cles)}</section><section class="info-card"><h2>Erreurs fréquentes</h2>${list(item.erreurs)}</section><section class="info-card"><h2>Respiration</h2><p>${esc(item.respiration)}</p></section><section class="info-card safety"><h2>Quand arrêter</h2><p>${esc(item.stop_rule)}</p></section><nav class="progression" aria-label="Progression du mouvement"><a class="progress-link${reg?'':' disabled'}" ${reg?`href="../${reg.slug}/"`:''}><small>Plus facile</small><strong>${reg?esc(reg.nom):"Pas de variante proposée"}</strong></a><a class="progress-link${prog?'':' disabled'}" ${prog?`href="../${prog.slug}/"`:''}><small>Plus difficile</small><strong>${prog?esc(prog.nom):"Progression par répétitions ou charge"}</strong></a></nav></div></div><aside class="animation-panel"><img src="../../${item.animation}" alt="Animation démontrant ${esc(item.nom)}" width="640" height="600"><p class="card-desc">Boucle pédagogique : observe surtout la trajectoire et le contrôle.</p></aside></div></div></main><footer class="site-footer"><div class="shell footer-inner"><span>RESET28 · Mouvement éducatif, non diagnostic.</span><a href="../../docs/sources.html">Sources & sécurité</a></div></footer></body></html>`;
}

await Promise.all([mkdir("data",{recursive:true}),mkdir("assets/animations",{recursive:true}),mkdir("clients/DEMO",{recursive:true}),mkdir("exercices",{recursive:true})]);
const publicRows=exercises.map(({animation_profile,...x})=>x);
await writeFile("data/exercises.json",JSON.stringify(publicRows,null,2)+"\n");
await writeFile("index.html",libraryPage(publicRows));
const bySlug=new Map(exercises.map(x=>[x.slug,x]));
for(const item of exercises){await mkdir(`exercices/${item.slug}`,{recursive:true});await writeFile(`exercices/${item.slug}/index.html`,exercisePage(item,bySlug));await writeFile(`assets/animations/${item.slug}.svg`,renderExerciseSvg(item));}
await writeFile("clients/DEMO/index.html",clientPage(demoProgram,publicRows));
await writeFile("clients/DEMO/program.json",JSON.stringify(demoProgram,null,2)+"\n");
const auditRows=animationAuditRows.map((row,index)=>`| ${index+1} | ${exercises.find(x=>x.slug===row.slug).nom} | ${row.description} | ${animationContrasts[row.slug]} |`).join("\n");
await writeFile("docs/AUDIT_ANIMATIONS.md",`# Audit visuel des 43 animations\n\nCritère : en masquant le nom de l'exercice, la position, le matériel et la trajectoire doivent permettre d'identifier raisonnablement le mouvement. Chaque ligne a été contrôlée sur les images de départ et d'arrivée, puis comparée aux 42 autres scènes.\n\n| # | Exercice | Lecture visuelle | Élément distinctif contrôlé |\n|---:|---|---|---|\n${auditRows}\n\nContrôle automatisé complémentaire : \`npm run check:animations\` vérifie la présence des 43 scènes, l'unicité de leur signature, les descriptions accessibles, les trajectoires et l'absence de SVG dupliqués.\n`);
console.log(`Build terminé : ${exercises.length} fiches et ${exercises.length} animations.`);
