export const animationContrasts={
  "assis-debout-chaise":"Départ réellement assis, contact visible avec l'assise, puis station debout.",
  "squat-chaise-controle":"Départ debout devant la chaise, hanches vers l'assise sans phase assise initiale.",
  squat:"Aucun matériel ; descente bilatérale symétrique vue de face.",
  "squat-goblet":"Charge unique maintenue contre la poitrine pendant toute la descente.",
  "fente-arriere-assistee":"Vue de profil avec une main constamment reliée au support vertical.",
  "fente-arriere":"Vue de profil, pas arrière visible et absence de support.",
  "split-squat":"Pieds déjà décalés au départ, fixes pendant la descente, haltères visibles.",
  "step-up-bas":"Marche rectangulaire et transfert vertical du corps sur le pied posé dessus.",
  "pont-fessier":"Dos et tête au sol, deux pieds au sol, aucun banc.",
  "hip-thrust":"Omoplates sur banc, deux pieds au sol, bassin montant sans charge.",
  "hip-thrust-charge":"Banc et barre avec deux disques clairement visibles au pli des hanches.",
  "hip-thrust-unilateral":"Banc, un seul pied au sol et seconde jambe tendue en l'air.",
  "mollets-debout":"Support latéral et élévation verticale du corps sur l'avant-pied.",
  "presse-a-cuisses":"Siège incliné, plateforme oblique et extension des deux jambes vers la plateforme.",
  "leg-curl-machine":"Assise horizontale, rouleau aux chevilles et talons allant sous le siège.",
  "pompes-murales":"Mains fixes sur un mur vertical et corps incliné qui s'en approche.",
  "pompes-inclinees-hautes":"Mains sur support haut ; angle du corps plus vertical que la variante standard.",
  "pompes-inclinees":"Mains sur support bas ; angle du corps plus proche du sol.",
  "pompes-genoux":"Genoux et mains en contact avec le tapis, pieds relâchés derrière.",
  pompes:"Mains et pointes de pieds au sol, corps entier descendant en bloc.",
  "chest-press-machine":"Position assise avec dossier et poignées poussées horizontalement devant la poitrine.",
  "developpe-halteres":"Corps allongé sur banc et deux haltères montant au-dessus de la poitrine.",
  "serrage-omoplates-debout":"Coudes pliés reculant sans élastique ni charge, omoplates signalées.",
  "tirage-serviette-isometrique":"Serviette visible entre les mains, tension extérieure puis tirage vers le buste.",
  "tirage-elastique":"Vue de profil face à un ancrage ; élastique horizontal et coudes longeant le corps.",
  "rowing-halteres-unilateral":"Buste penché, une main sur support et un seul haltère tiré vers la hanche.",
  "rowing-machine":"Position assise face à la colonne de câble et tirage horizontal des deux mains.",
  "tirage-vertical":"Cadre de poulie haute, barre large et trajectoire verticale vers la poitrine.",
  "pull-apart-elastique":"Vue de face, élastique entre les mains et ouverture horizontale des bras.",
  "glisse-murale-scapulaire":"Mur derrière le corps et avant-bras glissant d'une forme W vers une forme Y.",
  "developpe-epaules-halteres":"Deux haltères aux épaules puis au-dessus de la tête, trajectoire verticale.",
  "elevation-laterale":"Haltères près des cuisses puis bras en croix, trajectoires latérales en arc.",
  "face-pull-elastique":"Ancrage à hauteur du visage et élastique tiré vers les tempes, coudes ouverts.",
  "dead-bug-talons":"Bras fixes vers le plafond ; un talon seul se déplace jusqu'au sol.",
  "dead-bug":"Un bras et la jambe opposée s'allongent simultanément.",
  "bird-dog":"Appui quadrupédique ; un bras et la jambe opposée s'étendent horizontalement.",
  "planche-murale":"Mise en place par recul des pieds, avant-bras fixés sur un mur vertical.",
  "planche-inclinee":"Mains fixées sur un support intermédiaire et bassin venant dans l'alignement.",
  planche:"Passage des genoux aux pointes de pieds avec maintien sur les avant-bras au sol.",
  "planche-laterale-genoux":"Appui latéral sur avant-bras et genoux pliés au sol ; bassin qui se soulève.",
  "planche-laterale":"Appui latéral sur avant-bras et pieds empilés ; jambes entièrement tendues.",
  "pallof-press-elastique":"Ancrage latéral, corps vu de face et mains allant de la poitrine vers l'avant sans rotation.",
  "farmer-walk":"Deux charges latérales lourdes et alternance visible des appuis de marche."
};
